### ISSUE TITLE
bson out of modules list

### ISSUE THREAD

**Issue by MARTIMM** [perl6/ecosystem#51]
The Module BSON is not shown in the modules list anymore at ```http://modules.perl6.org/``` and I get the following error when installing MongoDB which depends on it

```
> panda install MongoDB
resolve stage failed for MongoDB: Dependency BSON is not present in the module ecosystem
...
```
I am now at the newest panda and perl6/moar version

**Comment by jonathanstowe** [comment]
Just sent you a pull request that should fix this.

**Comment by ugexe** [comment]
BSON has other problems as well. While panda may be installing this correctly for you, it cannot actually determine the proper build order and the fact it may be built in the proper order is a coincidence. 

package BSON { class Bson {

And then in your META you point at BSON::Bson. But both panda and Zef determine the build order by running a regex on the source.

**Comment by MARTIMM** [comment]
I've seen this before but I think I do not understand the implications of this.
I am using classes in packages constructs as I feel that it is just that 'a packagage with a set of modules and classes for some project'.

so therefore I use
```package BSON { class Bson {```

How do I have to change this? And, more importantly, Can one not use above structures?
It also can become harder for panda when one uses
```package X { module Y { class Z {```

**Comment by ugexe** [comment]
Theoretically its a sound practice.

The problem is that package managers need to determine the order to build the modules listed in `provides`, and this gets done by grepping the source for `use ModuleName` (thats over simplified) and counting the occurances each `use ModuleName`. Then it can compare against the count of `use OtherModule`. Now, the package manager *can* know that lib/BSON.pm contains `BSON::Bson` (the provides tells us), But lets say you have:
`package X { class Y {}; class Z {}; };`
First, both X::Y and X::Z would need to be mapped in the provides section. If we are to assume this is the case, then the next problem is panda will count `use X::Y; use X::Z` in the same script as 2 counts (and as such the build order may be changed)

**Comment by MARTIMM** [comment]
Thanks for the explanation, still have the following problem while installing from local directory...
```
> cd BSON
> panda install .
==> Installing BSON from a local directory '.'
==> Fetching BSON
==> Building BSON
Compiling lib/BSON/Exception.pm6 to mbc
Compiling lib/BSON/ObjectId.pm to mbc
Compiling lib/BSON/Regex.pm to mbc
Compiling lib/BSON/Javascript.pm to mbc
Compiling lib/BSON/Binary.pm to mbc
===SORRY!===
When pre-compiling a module, its dependencies must be pre-compiled first.
Please pre-compile /home/marcel/Languages/Perl6/Projects/BSON/.panda-work/1438847789_1/lib/BSON/EDC-Tools.pm6
==> Test report submitted as: http://testers.perl6.org/reports/</html>.html
build stage failed for BSON: Failed building lib/BSON/Binary.pm
  in method throw at /home/marcel/Software/lib/perl6/share/perl6/runtime/CORE.setting.moarvm:1
  in method install at lib/Panda.pm:128
  in method resolve at lib/Panda.pm:218
  in sub MAIN at /home/marcel/Software/lib/perl6/bin/panda:20
  in block <unit> at /home/marcel/Software/lib/perl6/bin/panda:87


Failure Summary
----------------
.
        *build stage failed for BSON: Failed building lib/BSON/Binary.pm
```
This is about what you've explained. Now how do I proceed to get this go away, Change the code into
something more 'panda comprehensable' or change the META.info

**Comment by jonathanstowe** [comment]
Hi,
I think it's actually a bug in the way that the Panda::Builder parses the "use" and "require" lines to get the module build order,  specifically it won't find any that have a '-' in their name as is the case with BSON::EDC-Tools - I've successfully built this with such a change.  I'll send you a PR that implements that but fixing "panda" might be a better idea.

**Comment by MARTIMM** [comment]
Found it, Looks like it must be the case. I will make an issue at panda
thanks

**Comment by jonathanstowe** [comment]
Hi, I just sent a PR to panda to fix this https://github.com/tadzik/panda/pull/197

**Comment by MARTIMM** [comment]
I've seen it, thanks. I've modified the code to load EDCTools as you suggested and it works fine. I will mention this at panda. I will close it now.

**Comment by jonathanstowe** [comment]
@tadzik has merged that change into panda so it should all be cool now anyway :)

**Comment by MARTIMM** [comment]
ok, so I can dash around now!
